## This Plugin was written by Robert Kratz on 11. Mai 2021
## You need help with setting up the Plugin? Check out my Discord: https://link.rjks.us/support

enabled: false

## Rank System Config

enable-rank-system: false
enable-tab-rank: false
enable-chat-rank: false

## We recommend to disable this function
display-effect-on-player: false
display-effect-on-top-while-sneaking: false

## Ingame Config

mlg-type-slot: 4
mlg-type-switch-sound: 'CLICK'

enable-player-joins-message: true
enable-player-leaves-message: true

block-material-from-jump: 'SANDSTONE'
block-duration-until-disapear: 5

min-height: 10
max-height: 255

game-action-bar-enabled: true
show-score-board: true

## This requires a minimum of 2 maps in the cache
map-change-counter-enabled: true
map-change-counter: 1800
map-change-counter-allow-two-maps-in-a-row: false

map-change-announcement-in-chat:
  - 500
  - 250
  - 100
  - 50
  - 30
  - 10
  - 5
  - 3
  - 2
  - 1

## If a Player executes the command /skip, the countdown will be set to the set number below
map-skip-countdown-to: 5
map-skip-countdown-possible-only-at-second: 100

permissions:
  operator: system.game.operator
  skip: system.game.cmd.skip
  always-skip: system.game.cmd.skip.always

mlg-items:
  - ==: org.bukkit.inventory.ItemStack
    type: WEB
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '&f&lCOBWEB'
  - ==: org.bukkit.inventory.ItemStack
    type: WATER_BUCKET
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '&b&lWATER'